CREATE TABLE USUARIOS;
USE USUARIOS;

INSERT INTO USUARIOS (NOMBREUSUARIO, PASSWORD, TIPO) VALUES ("usuarioadmin", 1234, "admin");
INSERT INTO USUARIOS (NOMBREUSUARIO, PASSWORD, TIPO) VALUES ("usuarionormal", 1234, "normal");